### ISSUE TITLE
Ungültige Mail Adresse verhindert weiteren Versand

### ISSUE THREAD

**Issue by mbmueller** [openjverein/jverein#209]
Wenn eine Mail an mehrere Empfänger gesendet werden soll und eine davon ungültig ist, wird der Versand endlos lange wiederholt versucht, was den Versand an alle anderen Empfänger verhindert. Auch herauszufinden, welche E-Mail ungültig ist ist nur über den Log möglich. Dieser sieht wie folgt aus:

`
 [Sun Apr 14 15:07:27 CEST 2024][INFO][main][de.willuhn.jameica.gui.internal.parts.BackgroundTaskMonitor$1$1.run] auto 
 closing monitor snapin
 [Sun Apr 14 15:07:35 CEST 2024][INFO][bg-task:][de.willuhn.jameica.gui.internal.parts.BackgroundTaskMonitor.check] 
 creating progress monitor for GUI
 [Sun Apr 14 15:07:35 CEST 2024][INFO][main][de.willuhn.jameica.gui.internal.parts.BackgroundTaskMonitor$2.run] activating 
 progress monitor
 [Sun Apr 14 15:07:35 CEST 2024][ERROR][bg-task:][de.jost_net.JVerein.gui.control.MailControl$4.run] 
 javax.mail.SendFailedException: Invalid Addresses;
   nested exception is:
	 com.sun.mail.smtp.SMTPAddressFailedException: 550 5.1.1 <Ungültige EMail-Adresse>: Recipient address rejected: 
 User unknown in virtual mailbox table

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2079)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1301)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:174)
	at de.jost_net.JVerein.io.MailSender.sendMail(MailSender.java:321)
	at de.jost_net.JVerein.io.MailSender.sendMail(MailSender.java:227)
	at de.jost_net.JVerein.gui.control.MailControl$4.run(MailControl.java:468)
	at de.willuhn.jameica.gui.GUI$7.run(GUI.java:1081)
 Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 5.1.1 <Ungültige Email-Adresse>: Recipient address 
 rejected: User unknown in virtual mailbox table

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1932)
	... 7 more
`

Edit: Irgendwie will die Formatierung als des Logs nicht so :(

**Comment by willuhn** [comment]
Derzeit wird vermutlich versucht, eine Mail an alle Empfänger zu senden. Die Fehlerbehandlung ist dann die interne in der SMTP-Implementierung von Java. Könnte man ggf. so umstellen, dass die Mails pro Empfänger in einer for-Schleife einzeln gesendet werden und jeweils mit einem try/catch umschlossen, sodass man anschließend ausgeben kann, an welchen Empfänger der Versand fehlschlug.

**Comment by JohannMaierhofer** [comment]
@mbmueller Wie machen wir hier weiter nachdem #215 geschlossen wurde? Evtl. Schließen?

**Comment by mbmueller** [comment]
Ja #215 sollte das Problem gelöst haben.
