### ISSUE TITLE
NoClassDefFoundError: javax/mail/internet/AddressException

### ISSUE THREAD

**Issue by stefanheinrichsen** [openjverein/jverein#226]
Wenn ich ein neues Mitglied abspeichern möcht taucht im Log folgende Meldung auf:

```
Wed May 08 13:12:43 CEST 2024][ERROR][main][de.willuhn.jameica.gui.GUI.loop] main loop crashed, retry
java.lang.NoClassDefFoundError: javax/mail/internet/AddressException
	at de.jost_net.JVerein.server.MitgliedImpl.plausi(MitgliedImpl.java:153)
	at de.jost_net.JVerein.server.MitgliedImpl.insertCheck(MitgliedImpl.java:91)
[...]
```
Es gibt keine Fehlermeldung im Programm selbst. Arbeite ich normal weiter stützt etwas später openJverein komplett ab.

Ich hab mir Zeile 153 der Datei angesehen und da wird die eMail Adresse geprüft. Gebe ich bei dem neuen Mitglied keine eMail Adresse ein wird das Mitglied ganz normal gespeichert. Ich vermute daher, dass da irgendene Java-Klasse ihren Namen geändert hat oder sowas.

Noch die Details zu meiner Umgebung:

```
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init] starting Jameica Version 2.8.6
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init]   Built-Date : 20191101
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init]   Buildnumber: 455
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init]   max. memory: 494mb
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init]   sys charset: windows-1252
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init] command line parameters
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init] os.arch          : x86
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init] os.name          : Windows 10
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init] os.version       : 10.0
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init] java.version     : 11.0.5
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init] java.vendor      : AdoptOpenJDK
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init] java.runtime.name: OpenJDK Runtime Environment
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init] java.vm.name     : OpenJDK Client VM
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init] user.name        : Stefan
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init] user.home        : C:\Users\Stefan
[Wed May 08 13:09:38 CEST 2024][INFO][main][de.willuhn.jameica.services.SysinfoService.init] file.encoding    : Cp1252
[...]

[Wed May 08 13:09:42 CEST 2024][INFO][main][de.willuhn.jameica.plugin.Manifest.<init>] hibiscus 2.10.20
[Wed May 08 13:09:42 CEST 2024][INFO][main][de.willuhn.jameica.plugin.Manifest.<init>]   Buildnumber: 384
[Wed May 08 13:09:42 CEST 2024][INFO][main][de.willuhn.jameica.plugin.Manifest.<init>]   Built-Date : 20240405
[Wed May 08 13:09:42 CEST 2024][INFO][main][de.willuhn.jameica.plugin.Manifest.<init>] jverein 2.8.21
[Wed May 08 13:09:42 CEST 2024][INFO][main][de.willuhn.jameica.plugin.Manifest.<init>]   Buildnumber: 523
[Wed May 08 13:09:42 CEST 2024][INFO][main][de.willuhn.jameica.plugin.Manifest.<init>]   Built-Date : 20240210
```

**Comment by willuhn** [comment]
Die Java-Klasse ist in jverein/lib/javax.mail-1.6.2.jar enthalten, welche von JVerein mitgebracht wird. Prüfe mal den Ordnerinhalt von Jameica und die Startausgaben von Jameica in der jameica.log - dort sollte die Datei auftauchen. Unter Umständen ist die Datei defekt oder fehlt aus irgend einem Grund.

**Comment by stefanheinrichsen** [comment]
Hm... nein, die Datei hat die gleiche Prüfsumme wie die Datei in dem aktuellen Release. Aber da der Issue geschlossen wurde vermute ich mal das es woanders nicht auftritt. Ich werde das ganze mal probeweise neu installieren. 

Die eMail Adresse die ich eigegeben hab ich natürlich eine "echte" Adresse. Daher kommt mir das weiterhin etwas merkwürdig vor. 

Aber wie gesagt: Ich versuche das ganze mal neu zu installieren und suche dann ggfs. weiter.

**Comment by willuhn** [comment]
Ja, ich habe es geschlossen, weil ich es nicht reproduzieren kann. Das hat eigentlich auch nicht mit der verwendeten Mailadresse zu tun. Ich sehe allerdings, dass deine Jameica-Version 2.8.6 ziemlich veraltet ist. Aktuell wäre 2.10.4. Das kann auch daran liegen.

**Comment by stefanheinrichsen** [comment]
Jawohl, das war es. Mit Jameica 2.10.4 funktioniert alles wieder. Danke. :-)
