### ISSUE TITLE
NullPointerException nach Schließen des Mailvorschaudialogs

### ISSUE THREAD

**Issue by tolot27** [openjverein/jverein#350]
Wenn ich den Mailvorschaudialog schließe, kommt folgende Exception bei den Systemmeldungen:

Quelle: `de.willuhn.jameica.gui.dialogs.AbstractDialog.close`
```java
error while notifying listeners
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Shell.getSize()" because the return value of "de.jost_net.JVerein.gui.dialogs.MailVorschauDialog.access$000(de.jost_net.JVerein.gui.dialogs.MailVorschauDialog)" is null
	at de.jost_net.JVerein.gui.dialogs.MailVorschauDialog$1.handleEvent(MailVorschauDialog.java:77)
	at de.willuhn.jameica.gui.dialogs.AbstractDialog.close(AbstractDialog.java:635)
	at de.jost_net.JVerein.gui.dialogs.MailVorschauDialog$2.handleAction(MailVorschauDialog.java:159)
	at de.willuhn.jameica.gui.parts.Button$1$1.run(Button.java:174)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:921)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4802)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:917)
	at de.willuhn.jameica.gui.parts.Button$1.widgetSelected(Button.java:168)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4273)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4071)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3659)
	at de.willuhn.jameica.gui.dialogs.AbstractDialog$4.run(AbstractDialog.java:564)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4802)
	at de.willuhn.jameica.gui.dialogs.AbstractDialog.open(AbstractDialog.java:489)
	at de.jost_net.JVerein.gui.dialogs.MailVorschauDialog.<init>(MailVorschauDialog.java:84)
	at de.jost_net.JVerein.gui.menu.MailAuswahlMenu$2.handleAction(MailAuswahlMenu.java:79)
	at de.willuhn.jameica.gui.parts.ContextMenu$1.handleEvent(ContextMenu.java:184)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4273)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4071)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3659)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:938)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:335)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:78)
```

**Comment by lenilsas** [comment]
Ich kann den Fehler nicht reproduzieren. Der Mailvorlagen Dialog kann an vielen verschiedenen stellen aufgerufen werden. An welchen stellen kommt bei dir die Exception? Schließt du mit Abbrechen oder mit ESC?

**Comment by tolot27** [comment]
> An welchen stellen kommt bei dir die Exception? Schließt du mit Abbrechen oder mit ESC?

Wenn ich im Navigationsbaum auf Mail klicke, eine Vorlage auswähle, einen Empfänger auswähle und dann auf dem Empfänger Rechtsklick mache und Vorschau anklicke (siehe auch drittes Bild im [JVerein Handbuch: Mail](https://openjverein.gitbook.io/doku/allgemeine-funktionen/druckmail/mail) gezeigt) . Nachdem ich den Dialog durch Klick auf Abbrechen (?) beende, wird die Exception geloggt.

**Comment by lenilsas** [comment]
Sorry ich hatte MailVorlage statt Mailvorschau gelesen... Jetzt habe ich den Fehler gefunden. Ich habe ihn in #353 behoben.
