### ISSUE TITLE
Diagnose-Backup Importreihenfolge und Probleme

### ISSUE THREAD

**Issue by tolot27** [openjverein/jverein#361]
Ich habe eben die Migration vom H2 backend zum MySQL backend durchgeführt. Dabei bin ich über folgende Probleme gestolpert:

1. Das Datenbankfeld `geschlecht` darf vor einem Export nicht `null` sein, sondern muss wenigstens auf `o` stehen, sonst kann ein Mitglied nicht importiert werden (das Tag `geschlecht` wird bei Null-Werten nämlich nicht ins XML exportiert). Das könnte als Followup zu #344 implementiert werden.
2. Das Datenbankfeld `zahlungsrhytmus` darf vor einem Export nicht `null` sein, sondern muss einen Wert enthalten, sonst wird das entsprechende XML-Tag nicht generiert und bei einem Import wird das Mitglied nicht angelegt. Bei allen Familienmitgliedern war bei mir das Feld `null` (waren zuvor aus CSV importiert).
3. Wenn das Datenbankfeld `geburtsdatum` `null` ist, werden die entsprechenden Mitglieder ignoriert. Hier kann man sich behelfen, indem man in den Anzeigeeinstellungen den Haken bei "Geburtsdatum Pflichtfeld" entfernt.
4. Die Einstellungen der Mitgliederverwaltung werden scheinbar nicht mit exportiert. Ansonsten würde 3. nicht auftreten.
5. Die Reihenfolge der Tabellenbefüllung scheint nicht optimal zu sein und führt zu foreign key constrains und somit unvollständigem Import. Konkret müssen Beitragsgruppen, Buchungsklassen und Buchungsarten importiert werden, bevor davon abhängige Tabellen importiert werden.

**Comment by lenilsas** [comment]
Habe ich in #363 behoben

**Comment by tolot27** [comment]
> Habe ich in #363 behoben

Man, ihr seid echt fix. 😄 

Eine weitere Sache ist mir noch aufgefallen. Wenn ich unter Mails eine (bereits versendete) Mail bearbeiten und abspeichern möchte, kommt untenstehende Exception, wenn das Backend MySQL ist. Das liegt daran, dass die Spalte `versand` in der Tabelle `mail` mit `Not Null` konfiguriert ist. In der H2 DB ist das nicht der Fall. Ich weiß nicht, mit welchem SQL Update-Skript das so gesetzt wird (habe die Skripte noch nicht gefunden). Bei einer frisch initialisierten MySQL DB Version 444 ist es jedenfalls `Not Null`. Lässt sich das auch noch beheben oder sollte das besser in ein anderes Ticket verschoben werden?

```java
Fehler bei speichern der Mail: update failed, rollback successful; nested exception is: 
	com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'versand' cannot be null
java.rmi.RemoteException: update failed, rollback successful; nested exception is: 
	com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'versand' cannot be null
	at de.willuhn.datasource.db.AbstractDBObject.update(AbstractDBObject.java:766)
	at de.willuhn.datasource.db.AbstractDBObject.store(AbstractDBObject.java:316)
	at de.jost_net.JVerein.gui.control.MailControl.handleStore(MailControl.java:565)
	at de.jost_net.JVerein.gui.control.MailControl$3.handleAction(MailControl.java:396)
	at de.willuhn.jameica.gui.parts.Button$1$1.run(Button.java:174)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:921)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4802)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:917)
	at de.willuhn.jameica.gui.parts.Button$1.widgetSelected(Button.java:168)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4273)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4071)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3659)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:938)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:335)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:78)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'versand' cannot be null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055)
	at de.willuhn.datasource.db.AbstractDBObject.update(AbstractDBObject.java:750)
	... 21 more
```

**Comment by lenilsas** [comment]
Das achaue ich mir an und würde einen extra PR dazu machen
