### ISSUE TITLE
Exception in MitgliedControl.handleStore: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by tolot27** [openjverein/jverein#544]
Ich habe gerade bei den Familienmitgliedern das Kündigungsdatum und Austrittsdatum eingetragen. Beim ersten Mitglied hat alles funktioniert. Beim zweiten Mitglied kam folgende Exception:

Quelle: de.jost_net.JVerein.gui.control.MitgliedControl.handleStore
Fehler bei Speichern des Mitgliedes
```java
java.rmi.RemoteException: Index 0 out of bounds for length 0
	at de.willuhn.datasource.db.DBIteratorImpl.next(DBIteratorImpl.java:264)
	at de.willuhn.datasource.db.DBIteratorImpl.next(DBIteratorImpl.java:30)
	at de.jost_net.JVerein.gui.control.MitgliedControl.handleStore(MitgliedControl.java:2462)
	at de.jost_net.JVerein.gui.view.AbstractMitgliedDetailView$2.handleAction(AbstractMitgliedDetailView.java:214)
	at de.willuhn.jameica.gui.parts.Button$1$1.run(Button.java:174)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:921)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4802)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:917)
	at de.willuhn.jameica.gui.parts.Button$1.widgetSelected(Button.java:168)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4273)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4071)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3659)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:938)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:335)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:78)
```

Ich habe es mehrfach versucht, bekomme jedoch immer wieder die Exception. Nachdem ich Jameica neugestartet habe, waren die Änderungen vorhanden. Also wurde gespeichert. Danach konnte ich weitere Familienmitglieder bearbeiten und speichern.

Ich versuche es mal zu reproduzieren. Aktuell ist bei mir noch 2.9.0-nightly f078676f installiert.

**Comment by lenilsas** [comment]
Das ist diese Codstelle
```
// Felddefinition ermitteln
          DBIterator<Felddefinition> it0 = Einstellungen.getDBService()
              .createList(Felddefinition.class);
          it0.addFilter("label = ?", new Object[] { ti.getName() });
          Felddefinition fd = it0.next();
```
Wir könnten ein `if(it0.hasNext())` einbauen. aber eigentlich sollte das nicht vorkommen, da `felddefinitionen` aus der DB gefüllt wird.

**Comment by lenilsas** [comment]
Tritt der Fehler noch auf?

**Comment by tolot27** [comment]
> Tritt der Fehler noch auf?

Der Fehler ist nicht nochmal aufgetreten.
