### ISSUE TITLE
Abbrechnung: Fehler bei zu langer E-Mail Adresse

### ISSUE THREAD

**Issue by dieseyer** [openjverein/jverein#86]
_https://doku.jverein.de/allgemeine-funktionen/mitglieder#grunddaten-des-mitglieds
Hinweis zur E-Mail-Adresse: In JVerein kann aktuell je Mitglied nur eine E-Mail-Adresse gespeichert werden. Hat ein Mitglied aber mehrere E-Mail-Adressen, kann man sich derzeit mit der 'Group'-Notation behelfen_

Das E-Mail - Feld in 'Abrechnung' ist kleiner als in 'Mitglieder'. Dadurch kann die Abrechnung mit einem Fehler abbrechen.

Lösungsvorschlag 1: Das Feld in Abrechnung auf die Größe in Mitglieder erhöhen.
Lösungsvorschlag 2: In der Abrechnung wird nur die erste E-Mail von der 'Group'-Notation verwendet.

(s. https://github.com/jverein/jverein/issues/85)

**Comment by dippeal** [comment]
Hast du ein Fehler-Log und/oder Screenshot zum Problem?

**Comment by dieseyer** [comment]
[jameica.log-20231103-1337_49.gz](https://github.com/openjverein/jverein/files/13474281/jameica.log-20231103-1337_49.gz)

```
[Thu Nov 02 14:15:11 CET 2023][ERROR][bg-task:][de.jost_net.JVerein.gui.control.AbrechnungSEPAControl$3.run] error while reading objects from /home/Temp/zw/abbuchungFRST-20231102-141438.XML
java.rmi.RemoteException: insert failed; nested exception is: 
	com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'email' at row 1
	at de.willuhn.datasource.db.AbstractDBObject.insert(AbstractDBObject.java:707)
	at de.willuhn.datasource.db.AbstractDBObject.store(AbstractDBObject.java:314)
	at de.jost_net.JVerein.io.AbrechnungSEPA.<init>(AbrechnungSEPA.java:218)
	at de.jost_net.JVerein.gui.control.AbrechnungSEPAControl$3.run(AbrechnungSEPAControl.java:476)
	at de.willuhn.jameica.gui.GUI$7.run(GUI.java:1069)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'email' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043)
	at de.willuhn.datasource.db.AbstractDBObject.insert(AbstractDBObject.java:655)
	... 4 more

[Thu Nov 02 14:15:36 CET 2023][INFO][main][de.jost_net.JVerein.JVereinPlugin.isArchiveServiceActive] Archiv-Plugin ist lokal installiert
```

**Comment by dippeal** [comment]
Wird mit nächstem release behoben sein.
