### ISSUE TITLE
Save and sending an email results in SecutityManager Exception

### ISSUE THREAD

**Issue by sagiru** [openjverein/jverein#99]
Hi,

i use jverein 2.8.20 with jameica 2.10.3 and java 11.0.18 on Debian 11. If i try to send an email i get the exception below. I tried to set the runtime logpath  at /etc/velocity/velocity.properties to /var/log/jameica/velocity.log but it doesn't change anything. Does someone a hint for me what i am doing wrong?

`sascha@kang:~/git/jameica$ grep runtime.log /etc/velocity/velocity.properties
runtime.log.logsystem.class = org.apache.velocity.runtime.log.AvalonLogChute,org.apache.velocity.runtime.log.Log4JLogChute,org.apache.velocity.runtime.log.CommonsLogLogChute,org.apache.velocity.runtime.log.ServletLogChute,org.apache.velocity.runtime.log.JdkLogChute
runtime.log = /var/log/jameica/velocity.log
runtime.log.invalid.references = true
`

## Exception:

`[Tue Jan 02 11:29:52 CET 2024][ERROR][bg-task:][de.jost_net.JVerein.gui.control.MailControl$4.run] 
org.apache.velocity.exception.VelocityException: Error initializing log: Failed to initialize an instance of org.apache.velocity.runtime.log.Log4JLogChute with the current runtime configuration.
	at org.apache.velocity.runtime.RuntimeInstance.initializeLog(RuntimeInstance.java:875)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:262)
	at org.apache.velocity.runtime.RuntimeSingleton.init(RuntimeSingleton.java:112)
	at org.apache.velocity.app.Velocity.init(Velocity.java:74)
	at de.jost_net.JVerein.gui.control.MailControl$4.run(MailControl.java:457)
	at de.willuhn.jameica.gui.GUI$7.run(GUI.java:1081)
Caused by: org.apache.velocity.exception.VelocityException: Failed to initialize an instance of org.apache.velocity.runtime.log.Log4JLogChute with the current runtime configuration.
	at org.apache.velocity.runtime.log.LogManager.createLogChute(LogManager.java:220)
	at org.apache.velocity.runtime.log.LogManager.updateLog(LogManager.java:269)
	at org.apache.velocity.runtime.RuntimeInstance.initializeLog(RuntimeInstance.java:871)
	... 5 more
Caused by: java.lang.SecurityException: Schreibzugriff auf /usr/share/jameica/velocity.log verweigert
	at de.willuhn.jameica.security.JameicaSecurityManager.checkFile(JameicaSecurityManager.java:150)
	at de.willuhn.jameica.security.JameicaSecurityManager.checkWrite(JameicaSecurityManager.java:74)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:225)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:158)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
	at org.apache.log4j.FileAppender.<init>(FileAppender.java:110)
	at org.apache.log4j.RollingFileAppender.<init>(RollingFileAppender.java:79)
	at org.apache.velocity.runtime.log.Log4JLogChute.initAppender(Log4JLogChute.java:118)
	at org.apache.velocity.runtime.log.Log4JLogChute.init(Log4JLogChute.java:85)
	at org.apache.velocity.runtime.log.LogManager.createLogChute(LogManager.java:157)
	... 7 more
Caused by: de.willuhn.util.ApplicationException: Schreibzugriff auf /usr/share/jameica/velocity.log verweigert
	at de.willuhn.jameica.security.JameicaSecurityManager.checkFile(JameicaSecurityManager.java:113)
	... 17 more
`

I tried also to set the permissions of /usr/share/jameica but it doesn't change anything too. I think the Security Manager blocks the path.

Regards
Sascha

**Comment by willuhn** [comment]
Ich nehme an, du verwendest Jameica aus den Paket-Repositories von Debian. Ich nehme an, in dem Paket ist irgendwas falsch konfiguriert worden. Kannst du mal die Jameica-Version als Download von www.willuhn.de testen? Denn eigentlich konfiguriert Jameica Velocity per "runtime.log.logsystem" intern so, dass dessen Logausgaben mit in ~/.jameica/jameica.log landen.

**Comment by sagiru** [comment]
Ja das klappt, ich hatte das Debian jameica und velocity Paket mit der neuesten Version von jverein von gitgub kombiniert. Hatte den Fehler leider falsch verortet. 

Vielen Dank, ich werde bei Debian noch einen Bug aufmachen :+1: 

Gruß
Sascha
